language: c
addons:
  apt:
    packages:
    - git
    - libasound2:i386
    - libcairo2:i386
    - libz1:i386
    - libbz2-1.0:i386
    - libssl1.0.0:i386
    - libfreetype6:i386
install:
  - git clone https://github.com/oliveiraallex/PharoImageCreatorForGithubCi.git
script:
  - cd PharoImageCreatorForGithubCi
  - bash imageCreate.sh
after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - ls -l
  - ls -l PharoImageCreatorForGithubCi
  - ls -l PharoImageCreatorForGithubCi/result/
  - bash upload.sh PharoImageCreatorForGithubCi/result/*
branches:
  except:
  - /^(?i:continuous)$/