jobs:
  include:
    - language: c
      addons:
        apt:
          packages:
          - git
          - libssl1.0.0:i386
      install:
        - git clone https://github.com/oliveiraallex/PharoImageCreatorForGithubCi.git
      script:
        -  bash PharoImageCreatorForGithubCi/imageCreate.sh
      after_success:
        - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
        - bash upload.sh result/*
      branches:
        except:
        - /^(?i:continuous)$/
