language: c
install:
  - git clone https://github.com/oliveiraallex/PharoImageCreatorForGithubCi.git
script:
  - ./PharoImageCreatorForGithubCi/imageCreate.sh
after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh PharoImageCreatorForGithubCi/result/*
branches:
  except:
  - /^(?i:continuous)$/